### PR TITLE
Add Instagram embed

### PR DESCRIPTION
**Pull request by Dhaulagiri**
Add logic and test to support lazy loading of Instagram videos

### CODE REVIEW

**Comment by poteto** [comment]
@Dhaulagiri Thanks! All looks good, could you also update the readme, perhaps with a list of providers?

**Comment by Dhaulagiri** [comment]
I added it to existing list along with an example @poteto .  If you want me to break it out more let me know.

**Comment by poteto** [comment]
@Dhaulagiri I just had a 27 hour flight, so I'll look through this tonight and push up a new release. Thanks for the initiative!

**Comment by Dhaulagiri** [comment]
No problem.  I hope you enjoyed your time in the States!

**Pull request merged**
